#Logistic_Regression

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score , recall_score

df = pd.read_csv("NIFTY22JANFUT.csv")
df.head(5)
del df['Unnamed: 0']
del df['dateTime']
df.head()
df['close_diff'] = df['close'].diff()
df.head()
df["new_col"] = np.where(df["close_diff"]>0,1,0)
df.head()
df.drop(df[df['close_diff'] == 0].index, inplace = True)
print(df)
X = df[['open' , 'high' ,'low' , 'close']] 
X.head()
y = df['new_col']
y.head()

clf_lrs = LogisticRegression()
clf_lrs.fit(X,y)

clf_lrs.predict_proba(X)
y_pred = clf_lrs.predict(X)
print(y_pred)





          open      high       low     close  volume  close_diff  new_col
0     17105.00  17129.95  17105.00  17106.15       0         NaN        0
1     17106.05  17116.00  17100.30  17116.00   12050        9.85        1
2     17116.15  17117.85  17102.70  17107.90    5800       -8.10        0
3     17107.90  17120.00  17107.90  17116.70    7450        8.80        1
4     17116.70  17116.70  17105.40  17106.10    4600      -10.60        0
...        ...       ...       ...       ...     ...         ...      ...
8296  17651.25  17653.55  17645.05  17647.65   44750       -6.35        0
8297  17647.95  17650.20  17645.00  17645.75   20550       -1.90        0
8298  17645.80  17650.00  17645.80  17650.00   34500        4.25        1
8299  17651.00  17651.00  17646.00  17647.75   43550       -2.25        0
8300  17647.35  17650.00  17644.00  17647.90   42150        0.15        1

[8130 rows x 7 columns]
[1 1 0 ... 1 0 1]


In [ ]:
print(precision_score(y , y_pred))
print(recall_score(y, y_pred))
print(clf_lrs.coef_)
print(clf_lrs.intercept_)

print(confusion_matrix(y , y_pred))



0.956685027541312
0.9283284742468416
[[-1.35335163  0.01192179 -0.02131859  1.36274275]]
[-0.00069882]
[[3841  173]
 [ 295 3821]]
